SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE customer (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  customer_no VARCHAR(32) NOT NULL COMMENT '客户号，样例业务键',
  customer_name_sample VARCHAR(80) NOT NULL COMMENT '样例客户名称，不是真实姓名',
  customer_type VARCHAR(16) NOT NULL DEFAULT 'PERSONAL' COMMENT '客户类型：PERSONAL/COMPANY',
  mobile_masked VARCHAR(32) NOT NULL COMMENT '脱敏手机号样例',
  id_no_masked VARCHAR(64) NOT NULL COMMENT '脱敏证件号样例',
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '客户状态：ACTIVE/FROZEN/CLOSED',
  current_risk_level VARCHAR(8) NOT NULL DEFAULT 'LOW' COMMENT '当前风险等级：LOW/MEDIUM/HIGH',
  current_risk_score DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '当前风险分数，0-100',
  last_risk_calculated_at DATETIME(3) NULL COMMENT '最近风险计算时间，UTC',
  remark_sample VARCHAR(200) NULL COMMENT '样例备注，不记录真实敏感信息',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间，UTC',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间，UTC',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_customer_no (customer_no),
  KEY idx_customer_name_sample (customer_name_sample),
  KEY idx_customer_risk_status (current_risk_level, status),
  KEY idx_customer_updated_at (updated_at),
  CONSTRAINT chk_customer_type CHECK (customer_type IN ('PERSONAL', 'COMPANY')),
  CONSTRAINT chk_customer_status CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED')),
  CONSTRAINT chk_customer_risk_level CHECK (current_risk_level IN ('LOW', 'MEDIUM', 'HIGH')),
  CONSTRAINT chk_customer_risk_score CHECK (current_risk_score >= 0 AND current_risk_score <= 100),
  CONSTRAINT chk_customer_deleted CHECK (deleted IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户基础信息样例表';

CREATE TABLE account (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  customer_no VARCHAR(32) NOT NULL COMMENT '客户号',
  account_no_masked VARCHAR(64) NOT NULL COMMENT '脱敏账号样例',
  account_type VARCHAR(16) NOT NULL DEFAULT 'DEBIT' COMMENT '账户类型：DEBIT/CREDIT/LOAN',
  currency CHAR(3) NOT NULL DEFAULT 'CNY' COMMENT '币种，ISO 4217',
  balance DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '账户余额',
  available_balance DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '可用余额',
  account_status VARCHAR(16) NOT NULL DEFAULT 'NORMAL' COMMENT '账户状态：NORMAL/FROZEN/CLOSED',
  has_abnormal_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否存在样例异常标记',
  opened_at DATE NOT NULL COMMENT '开户日期，样例数据',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间，UTC',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间，UTC',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除',
  PRIMARY KEY (id),
  UNIQUE KEY uk_account_no_masked (account_no_masked),
  KEY idx_account_customer_no (customer_no),
  KEY idx_account_status (account_status),
  KEY idx_account_abnormal (has_abnormal_flag),
  CONSTRAINT fk_account_customer_no FOREIGN KEY (customer_no) REFERENCES customer (customer_no),
  CONSTRAINT chk_account_type CHECK (account_type IN ('DEBIT', 'CREDIT', 'LOAN')),
  CONSTRAINT chk_account_status CHECK (account_status IN ('NORMAL', 'FROZEN', 'CLOSED')),
  CONSTRAINT chk_account_abnormal CHECK (has_abnormal_flag IN (0, 1)),
  CONSTRAINT chk_account_deleted CHECK (deleted IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='账户样例表';

CREATE TABLE risk_record (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  customer_no VARCHAR(32) NOT NULL COMMENT '客户号',
  risk_level VARCHAR(8) NOT NULL COMMENT '风险等级：LOW/MEDIUM/HIGH',
  risk_score DECIMAL(5,2) NOT NULL COMMENT '风险分数，0-100',
  risk_reason_sample VARCHAR(500) NOT NULL COMMENT '样例风险原因，不包含真实风控信息',
  rule_code VARCHAR(32) NOT NULL DEFAULT 'DEMO_RULE_V1' COMMENT '样例规则编号',
  source_type VARCHAR(16) NOT NULL DEFAULT 'MANUAL' COMMENT '来源：INIT/MANUAL/SCHEDULED',
  calculated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '计算人或操作人',
  calculated_at DATETIME(3) NOT NULL COMMENT '计算时间，UTC',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间，UTC',
  PRIMARY KEY (id),
  KEY idx_risk_customer_time (customer_no, calculated_at DESC, id DESC),
  KEY idx_risk_level_time (risk_level, calculated_at DESC),
  CONSTRAINT fk_risk_customer_no FOREIGN KEY (customer_no) REFERENCES customer (customer_no),
  CONSTRAINT chk_risk_level CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH')),
  CONSTRAINT chk_risk_score CHECK (risk_score >= 0 AND risk_score <= 100),
  CONSTRAINT chk_risk_source CHECK (source_type IN ('INIT', 'MANUAL', 'SCHEDULED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='风险评级历史样例表';

CREATE TABLE operation_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  request_id VARCHAR(64) NOT NULL COMMENT '请求追踪号',
  operator VARCHAR(64) NOT NULL COMMENT '操作人，来自固定值或X-Operator',
  operation_type VARCHAR(32) NOT NULL COMMENT '操作类型：QUERY_CUSTOMER/UPDATE_CUSTOMER/RECALCULATE_RISK/QUERY_LOG',
  target_type VARCHAR(32) NOT NULL COMMENT '目标类型：CUSTOMER/ACCOUNT/RISK/LOG',
  target_biz_no VARCHAR(64) NULL COMMENT '目标业务号，例如客户号或脱敏账号',
  result VARCHAR(16) NOT NULL DEFAULT 'SUCCESS' COMMENT '结果：SUCCESS/FAIL',
  error_message_sample VARCHAR(500) NULL COMMENT '样例错误信息，不记录堆栈和敏感字段',
  operation_desc_sample VARCHAR(500) NULL COMMENT '样例操作描述，不记录敏感明文',
  client_ip_masked VARCHAR(64) NULL COMMENT '脱敏客户端地址样例',
  duration_ms INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '耗时，毫秒',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间，UTC',
  PRIMARY KEY (id),
  KEY idx_op_request_id (request_id),
  KEY idx_op_operator_time (operator, created_at DESC),
  KEY idx_op_target (target_type, target_biz_no),
  KEY idx_op_type_time (operation_type, created_at DESC),
  CONSTRAINT chk_operation_result CHECK (result IN ('SUCCESS', 'FAIL'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作日志样例表';
